#To create a debug executable, run with the command:
# make DEBUG

CC            = gcc
CFLAGS        = -c -O -I.
CFLAGS-DEBUG  = -c -g -I.
LINK          = gcc
LFLAGS        =
LFLAGS-DEBUG  =
LIBS          = -L. -lslang
SRC           = dernc.c memfile.c graffiti.c main.c input_kb.c scr_help.c var_utils.c output_scr.c scr_thing.c graffiti_font.c bulcommn.c lev_data.c lev_files.c obj_slabs.c obj_things.c obj_column.c obj_actnpts.c lev_things.c lev_column.c obj_column_def.c obj_column_per.c scr_list.c scr_slab.c scr_clm.c scr_actn.c scr_txted.c lev_script.c scr_rwrk.c scr_cube.c draw_map.c xtabdat8.c xtabjty.c xcubtxtr.c
OBJ           = $(SRC:.c=.o)
BIN           = map
RM            = rm -f

all: $(SRC) $(BIN)

$(BIN): $(OBJ)
   $(LINK) $(if $(filter yes, $(DEBUGME)),$(LFLAGS-DEBUG),$(LFLAGS)) -o $@ $(OBJ) $(LIBS)

.c.o:
   $(CC) $(if $(filter yes, $(DEBUGME)),$(CFLAGS-DEBUG),$(CFLAGS)) $< -o $@

clean:
   find . -name \*~ -print | xargs ${RM}
   find . -name \*.o -print | xargs ${RM}
   find . -name \*.a -print | xargs ${RM}
   find . -name \*.dep -print | xargs ${RM}
   ${RM} $(BIN)
